# Generated by Django 4.2.4 on 2023-09-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_productmovement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductMovement',
        ),
    ]
