# Generated by Django 4.2.4 on 2023-09-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=500)),
                ('qty', models.IntegerField()),
            ],
        ),
    ]
